backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'static/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections: